Repository meshtastic/network-management-client, pull requests merged in 2022-10, with the labels that each got.

#8 Initialize ESLint Configuration
  .eslintrc.json
  .prettierrc
  .vscode/settings.json
  README.md
  package.json
  pnpm-lock.yaml
  src/App.css
  src/pages/_app.tsx
  src/pages/index.tsx
  src/style.css
Labels: enhancement, productivity

#9 Initialize Redux Store
  .eslintrc.json
  package.json
  pnpm-lock.yaml
  src/features/counter/counterSlice.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/store/index.ts
  tsconfig.json
Labels: enhancement

#10 Add Redux Saga Framework
  .eslintrc.json
  .prettierrc
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
  src/features/demoAPI/demoAPIActions.ts
  src/features/demoAPI/demoAPISaga.ts
  src/pages/index.tsx
  src/store/index.ts
  src/store/saga.ts
Labels: enhancement

#25 Migrate to Vite
  .eslintrc.cjs
  .eslintrc.json
  .gitignore
  .prettierrc
  .vscode/settings.json
  index.html
  next-env.d.ts
  next.config.js
  package.json
  pnpm-lock.yaml
  prettier.config.cjs
  public/vite.svg
  src-tauri/.gitignore
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/icons/128x128.png
  src-tauri/icons/128x128@2x.png
  src-tauri/icons/32x32.png
  src-tauri/icons/Square107x107Logo.png
  src-tauri/icons/Square142x142Logo.png
  src-tauri/icons/Square150x150Logo.png
  src-tauri/icons/Square284x284Logo.png
  src-tauri/icons/Square30x30Logo.png
  src-tauri/icons/Square310x310Logo.png
  src-tauri/icons/Square44x44Logo.png
  src-tauri/icons/Square71x71Logo.png
  src-tauri/icons/Square89x89Logo.png
  src-tauri/icons/StoreLogo.png
  src-tauri/icons/icon.icns
  src-tauri/icons/icon.ico
  src-tauri/icons/icon.png
  src-tauri/tauri.conf.json
  src/App.css
  src/App.tsx
  src/assets/next.svg
  src/assets/tauri.svg
  src/features/counter/counterSlice.ts
  src/features/demoAPI/demoAPIActions.ts
  src/features/demoAPI/demoAPISaga.ts
  src/index.css
  src/main.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/store/index.ts
  src/store/saga.ts
  src/style.css
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: enhancement

#26 Implement demo rust unit testing
  README.md
  package.json
  src-tauri/src/main.rs
Labels: enhancement, testing

#45 Implemented Graph DS in Rust
  src-tauri/src/graph.rs
  src-tauri/src/main.rs
Labels: enhancement

#49 Graph DS using Petgraph Library
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/src/graph.rs
  src-tauri/src/graph_p.rs
  src-tauri/src/main.rs
Labels: enhancement

#55 Add working Protobuf Compilation
  .gitmodules
  .vscode/settings.json
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/build.rs
  src-tauri/src/lib.rs
  src-tauri/src/main.rs
  src/App.tsx
Labels: enhancement, productivity
