Repository meshtastic/network-management-client, pull requests merged in 2022-11, with the labels that each got.

#53 Implemented Tarjan's Algo for Articulation Points
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/src/articulation_point.rs
  src-tauri/src/graph_p.rs
  src-tauri/src/main.rs
Labels: enhancement

#56 Initial Jest Setup
  .eslintrc.cjs
  README.md
  jest.config.cjs
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/features/counter/counterSlice.ts
  src/features/counter/counterslice.spec.ts
  src/features/demoAPI/demoAPISaga.ts
  tsconfig.json
Labels: testing

#60 Add Sidebar Menu
  index.html
  package.json
  pnpm-lock.yaml
  postcss.config.cjs
  src/App.css
  src/App.tsx
  src/Components/Map.tsx
  src/assets/Mesh_Logo_White.svg
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/SidebarIcon.tsx
  src/index.css
  tailwind.config.cjs
Labels: enhancement

#69 Fixed module hierarchy
  src-tauri/src/algorithms/GLOBALMINCUT.md
  src-tauri/src/algorithms/articulation_point.rs
  src-tauri/src/algorithms/globalmincut.rs
  src-tauri/src/algorithms/mod.rs
  src-tauri/src/graph/edge.rs
  src-tauri/src/graph/graph_ds.rs
  src-tauri/src/graph/mod.rs
  src-tauri/src/graph/node.rs
  src-tauri/src/main.rs
Labels: productivity

#70 Added Styled Map Zoom and Scale Elements
  src/App.tsx
  src/Components/Map.tsx
  src/Components/Map/Map.css
  src/Components/Map/Map.tsx
  src/main.tsx
  tsconfig.json
Labels: enhancement

#79 Implemented Stoer-Wagner Algorithm
  src-tauri/src/algorithms/articulation_point.rs
  src-tauri/src/algorithms/globalmincut.rs
  src-tauri/src/algorithms/mod.rs
  src-tauri/src/algorithms/stoer_wagner.rs
  src-tauri/src/aux_data_structures/binary_heap.rs
  src-tauri/src/aux_data_structures/cut.rs
  src-tauri/src/aux_data_structures/mod.rs
  src-tauri/src/aux_data_structures/stoer_wagner_ds.rs
  src-tauri/src/aux_data_structures/union_find.rs
  src-tauri/src/graph/graph_ds.rs
  src-tauri/src/graph/node.rs
  src-tauri/src/main.rs
Labels: enhancement

#80 Added function to recover the mincut
  src-tauri/src/algorithms/stoer_wagner.rs
Labels: enhancement

#82 Added module to merge and normalize edge weights
  src-tauri/src/algorithms/stoer_wagner.rs
  src-tauri/src/aux_functions/edge_factory.rs
  src-tauri/src/aux_functions/mod.rs
  src-tauri/src/main.rs
Labels: enhancement

#78 Add Node Icons to Map
  src/App.tsx
  src/Components/Map/Map.tsx
  src/Components/Map/MapNode.tsx
  src/Components/Map/MapNodeIcon.tsx
  src/Components/Map/MapView.css
  src/Components/Map/MapView.tsx
  src/assets/map-nodes/Size=Large, State=Error, IsBase=False.svg
  src/assets/map-nodes/Size=Large, State=Nominal, IsBase=False.svg
  src/assets/map-nodes/Size=Large, State=Selected, IsBase=False.svg
  src/assets/map-nodes/Size=Large, State=Warning, IsBase=False.svg
  src/assets/map-nodes/Size=Medium, State=Error, IsBase=False.svg
  src/assets/map-nodes/Size=Medium, State=Nominal, IsBase=False.svg
  src/assets/map-nodes/Size=Medium, State=Nominal, IsBase=True.svg
  src/assets/map-nodes/Size=Medium, State=Selected, IsBase=False.svg
  src/assets/map-nodes/Size=Medium, State=Warning, IsBase=False.svg
  src/assets/map-nodes/Size=Small, State=Error, IsBase=False.svg
  src/assets/map-nodes/Size=Small, State=Nominal, IsBase=False.svg
  src/assets/map-nodes/Size=Small, State=Selected, IsBase=False.svg
  src/assets/map-nodes/Size=Small, State=Warning, IsBase=False.svg
  src/index.css
  src/main.tsx
  tsconfig.json
  vite.config.ts
Labels: enhancement

#86 Integrate Live Device Data
  package.json
  pnpm-lock.yaml
  src/Components/Map/MapNode.tsx
  src/Components/Map/MapView.tsx
  src/components/Sidebar/Sidebar.tsx
  src/features/device/deviceActions.ts
  src/features/device/deviceConnectionHandlerSagas.ts
  src/features/device/deviceSagas.ts
  src/features/device/deviceSelectors.ts
  src/features/device/deviceSlice.ts
  src/store/index.ts
  src/store/saga.ts
Labels: enhancement

#91 Display All Nodes on Map
  src/Components/Map/MapNode.tsx
  src/Components/Map/MapView.tsx
  src/features/device/deviceConnectionHandlerSagas.ts
  src/features/device/deviceSelectors.ts
  src/features/device/deviceSlice.ts
Labels: enhancement

#93 Add another scaler to radio_signal_quality for a better scaling of the features
  src-tauri/src/aux_functions/edge_factory.rs
Labels: enhancement

#111 Added Node Search Pane
  src/components/Map/MapIconButton.tsx
  src/components/Map/MapNode.tsx
  src/components/Map/MapNodeIcon.tsx
  src/components/Map/MapView.tsx
  src/components/NodeSearch/NodeSearchDock.tsx
  src/components/NodeSearch/NodeSearchInput.tsx
  src/components/NodeSearch/NodeSearchResult.tsx
  src/components/Sidebar/Sidebar.tsx
  src/features/device/deviceSelectors.ts
  src/features/device/deviceSlice.ts
  src/index.css
  src/utils/nodeUtils.ts
  tsconfig.json
  vite.config.ts
Labels: enhancement

#115 Move Sidebar State into Redux
  src/components/Map/MapView.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/SidebarIcon.tsx
  src/features/device/deviceSlice.ts
  src/features/panels/panelsSelectors.ts
  src/features/panels/panelsSlice.ts
  src/store/index.ts
Labels: enhancement

#125 Refresh Node Timeout Value
  src/components/Map/MapNode.tsx
  src/components/NodeSearch/NodeSearchResult.tsx
Labels: enhancement

#135 Fixed settings bug
  src/components/Map/MapView.tsx
Labels: bug
