Repository meshtastic/network-management-client, pull requests merged in 2023-01, with the labels that each got.

#161 Fix Windows serial connection bug
  src-tauri/src/main.rs
  src-tauri/src/mesh/serial_connection.rs
  src/components/Messages/Messages.tsx
Labels: bug, high priority

#194 Implement notifications for tauri app
  package.json
  pnpm-lock.yaml
  src/components/Map/MapInteractionPane.tsx
  src/main.tsx
Labels: enhancement

#195 Reads active node info, sets as default values for device config
  package.json
  pnpm-lock.yaml
  src/components/Settings/Settings.tsx
  src/main.tsx
Labels: enhancement

#212 Add Config and User Update Infrastructure
  src-tauri/src/main.rs
  src-tauri/src/mesh/device/connection.rs
  src-tauri/src/mesh/device/handlers.rs
  src-tauri/src/mesh/device/helpers.rs
  src-tauri/src/mesh/device/mod.rs
  src-tauri/src/mesh/device/state.rs
  src-tauri/src/mesh/mod.rs
  src-tauri/src/mesh/serial_connection.rs
Labels: enhancement

#231 Creating and styling onboarding page for client.
  pnpm-lock.yaml
  src/App.tsx
  src/assets/Mesh_Logo_Black.png
  src/assets/onboard_hero_image.jpg
  src/components/Onboard/SerialPortOption.tsx
  src/components/pages/Meshtastic-emergency-client.code-workspace
  src/components/pages/OnboardPage.tsx
Labels: ui

#232 Add request (command) state management
  src/features/device/deviceConnectionHandlerSagas.ts
  src/features/device/deviceSagas.ts
  src/features/requests/requestReducer.ts
  src/features/requests/requestSelectors.ts
  src/store/index.ts
Labels: enhancement

#242 Initial messaging view layout
  src-tauri/bindings/ChannelMessagePayload.ts
  src-tauri/src/mesh/device/state.rs
  src/App.tsx
  src/components/Map/MapView.tsx
  src/components/Messaging/ChannelListElement.tsx
  src/components/Messaging/ChatBubble.tsx
  src/components/Messaging/Messages.tsx
  src/components/NavigationBacktrace.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/pages/Meshtastic-emergency-client.code-workspace
  src/components/pages/MessagingPage.tsx
  src/features/device/deviceSelectors.ts
Labels: enhancement
